
; FASM SOURCE FILE
; http://flatassembler.net

; written by @L.CHEMIST (Andrey A. Meshkov)
; maalchemist@gmail.com
; maa-mail@yandex.ru

; ------------------------------------------------------------------------------

STATUS_SUCCESS         = 0
STATUS_UNSUCCESSFUL    = 0xC0000001
STATUS_NOT_IMPLEMENTED = 0xC0000002

; ------------------------------------------------------------------------------
